In [1]:
pip install pydataset

Requirement already satisfied: pydataset in c:\users\manish\anaconda3\lib\site-packages (0.2.0)
Requirement already satisfied: pandas in c:\users\manish\anaconda3\lib\site-packages (from pydataset) (1.3.4)
Requirement already satisfied: numpy>=1.17.3 in c:\users\manish\anaconda3\lib\site-packages (from pandas->pydataset) (1.20.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\manish\anaconda3\lib\site-packages (from pandas->pydataset) (2.7.5)
Requirement already satisfied: pytz>=2017.3 in c:\users\manish\anaconda3\lib\site-packages (from pandas->pydataset) (2021.3)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: six>=1.5 in c:\users\manish\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->pydataset) (1.16.0)

[notice] A new release of pip is available: 23.0 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
from pydataset import data
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
data()

        dataset_id                                             title
0    AirPassengers       Monthly Airline Passenger Numbers 1949-1960
1          BJsales                 Sales Data with Leading Indicator
2              BOD                         Biochemical Oxygen Demand
3     Formaldehyde                     Determination of Formaldehyde
4     HairEyeColor         Hair and Eye Color of Statistics Students
..             ...                                               ...
752        VerbAgg                  Verbal Aggression item responses
753           cake                 Breakage Angle of Chocolate Cakes
754           cbpp                 Contagious bovine pleuropneumonia
755    grouseticks  Data on red grouse ticks from Elston et al. 2001
756     sleepstudy       Reaction times in a sleep deprivation study

[757 rows x 2 columns]

In [9]:
df =data("DoctorAUS")
df.head()

,sex,age,income,insurance,illness,actdays,hscore,chcond,doctorco,nondocco,hospadmi,hospdays,medecine,prescrib,nonpresc
1,1,0.19,0.55,levyplus,1,4,1,np,1,0,0,0,1,1,0
2,1,0.19,0.45,levyplus,1,2,1,np,1,0,0,0,2,1,1
3,0,0.19,0.90,medlevy,3,0,0,np,1,0,1,4,2,1,1
4,0,0.19,0.15,medlevy,1,0,0,np,1,0,0,0,0,0,0
5,0,0.19,0.45,medlevy,2,5,1,la,1,0,0,0,3,1,2

In [10]:
df.corr() #predictiing insurance type

,sex,age,income,illness,actdays,hscore,doctorco,nondocco,hospadmi,hospdays,medecine,prescrib,nonpresc
sex,1.000000,0.281136,-0.276606,0.134814,0.041046,0.057420,0.078637,0.075937,0.037183,0.026237,0.267897,0.270397,0.048157
age,0.281136,1.000000,-0.271073,0.204984,0.094745,0.018616,0.124537,0.118061,0.071902,0.115854,0.376949,0.432989,-0.036589
income,-0.276606,-0.271073,1.000000,-0.148812,-0.047545,-0.085790,-0.076840,-0.065338,-0.073705,-0.087712,-0.160023,-0.195039,0.037836
illness,0.134814,0.204984,-0.148812,1.000000,0.218116,0.360110,0.223552,0.114348,0.150823,0.118544,0.456117,0.422596,0.157048
actdays,0.041046,0.094745,-0.047545,0.218116,1.000000,0.280208,0.418954,0.226977,0.258456,0.189180,0.246586,0.251440,0.039255
hscore,0.057420,0.018616,-0.085790,0.360110,0.280208,1.000000,0.193272,0.121585,0.165882,0.118399,0.225632,0.199796,0.096075
doctorco,0.078637,0.124537,-0.076840,0.223552,0.418954,0.193272,1.000000,0.148052,0.248410,0.141771,0.273022,0.307779,-0.014914
nondocco,0.075937,0.118061,-0.065338,0.114348,0.226977,0.121585,0.148052,1.000000,0.152082,0.171403,0.152600,0.163349,0.008903
hospadmi,0.037183,0.071902,-0.073705,0.150823,0.258456,0.165882,0.248410,0.152082,1.000000,0.495569,0.200588,0.222882,-0.004515
hospdays,0.026237,0.115854,-0.087712,0.118544,0.189180,0.118399,0.141771,0.171403,0.495569,1.000000,0.158207,0.180540,-0.012997
medecine,0.267897,0.376949,-0.160023,0.456117,0.246586,0.225632,0.273022,0.152600,0.200588,0.158207,1.000000,0.889358,0.418126
prescrib,0.270397,0.432989,-0.195039,0.422596,0.251440,0.199796,0.307779,0.163349,0.222882,0.180540,0.889358,1.000000,-0.043462
nonpresc,0.048157,-0.036589,0.037836,0.157048,0.039255,0.096075,-0.014914,0.008903,-0.004515,-0.012997,0.418126,-0.043462,1.000000

In [56]:
#split into dependent and independent variables
x=df[["age","income","sex","illness","actdays","hscore","doctorco","nondocco","hospadmi","hospdays","medecine","prescrib"]]
y=df['insurance']

In [57]:
#splitting data into training and testing
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=1)

In [58]:
x_train.shape #check training shape

(4152, 12)

In [59]:
x_test.shape #check test shape

(1038, 12)

In [60]:
clf =GaussianNB()

In [61]:
#training
clf.fit(x_train,y_train)

GaussianNB()

In [62]:
y_pr =clf.predict(x_test)
y_pr

array(['medlevy', 'levyplus', 'medlevy', ..., 'medlevy', 'freepor',
       'medlevy'], dtype='<U8')

In [64]:
print(classification_report(y_test,y_pr))

              precision    recall  f1-score   support

     freepor       0.23      0.14      0.17        44
    freerepa       0.68      0.53      0.60       220
    levyplus       0.52      0.35      0.42       455
     medlevy       0.47      0.79      0.59       319

    accuracy                           0.51      1038
   macro avg       0.48      0.45      0.44      1038
weighted avg       0.53      0.51      0.50      1038